require "settings"
require "plugins-list"
require "keymappings"

-- Plugins
require "plugins.nvimnotify"
require "plugins.nvimtree"
require "plugins.nvimbufferline"
require "plugins.lualine"
require "plugins.dashboard"
require "plugins.treesitter"
require "plugins.cmp"
require "plugins.autopairs"
require "plugins.gitsigns"
require "plugins.telescope"
require "plugins.whichkey"

require "lsp"
require "colorscheme"
require "autocmds"
